export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
  NOT_ENOUGH_MEMES: "NOT_ENOUGH_MEMES",
  MATCHUP_NOT_PENDING: "MATCHUP_NOT_PENDING",
  INVALID_WINNER: "INVALID_WINNER",
  OAUTH_FAILED: "OAUTH_FAILED",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
